package creative.user.model;

import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

/**
 *
 *
 */
@DynamoDBTable(tableName = "AccessToken")
public class AccessToken {
  private String mTokenValue;
  private String mUserId;
  private long mCreatedTimestamp;
  private long mExpiryTimestamp;
  private String mClientAddress;
  private String mClientHostname;

  public AccessToken() {
    super();
    mCreatedTimestamp = System.currentTimeMillis();
  }

  public AccessToken(final String pUserId) {
    this();
    mUserId = pUserId;
  }

  @Override
  public int hashCode() {
    return HashCodeBuilder.reflectionHashCode(17, 37, this);
  }

  @Override
  public String toString() {
    return ToStringBuilder.reflectionToString(this);
  }

  /**
   * @return the tokenValue
   */
  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  public String getTokenValue() {
    return mTokenValue;
  }

  /**
   * @param pTokenValue
   *          the tokenValue to set
   */
  public void setTokenValue(final String pTokenValue) {
    mTokenValue = pTokenValue;
  }

  /**
   * @return the userId
   */
  @DynamoDBAttribute
  public String getUserId() {
    return mUserId;
  }

  /**
   * @param pUserId
   *          the userId to set
   */
  public void setUserId(final String pUserId) {
    mUserId = pUserId;
  }

  /**
   * @return the createdTimestamp
   */
  public long getCreatedTimestamp() {
    return mCreatedTimestamp;
  }

  /**
   * @param pCreatedTimestamp
   *          the createdTimestamp to set
   */
  public void setCreatedTimestamp(final long pCreatedTimestamp) {
    mCreatedTimestamp = pCreatedTimestamp;
  }

  /**
   * @return the expiryTimestamp
   */
  public long getExpiryTimestamp() {
    return mExpiryTimestamp;
  }

  /**
   * @param pExpiryTimestamp
   *          the expiryTimestamp to set
   */
  public void setExpiryTimestamp(final long pExpiryTimestamp) {
    mExpiryTimestamp = pExpiryTimestamp;
  }

  /**
   * @return the clientAddress
   */
  public String getClientAddress() {
    return mClientAddress;
  }

  /**
   * @param pClientAddress
   *          the clientAddress to set
   */
  public void setClientAddress(final String pClientAddress) {
    mClientAddress = pClientAddress;
  }

  /**
   * @return the clientHostname
   */
  public String getClientHostname() {
    return mClientHostname;
  }

  /**
   * @param pClientHostname
   *          the clientHostname to set
   */
  public void setClientHostname(final String pClientHostname) {
    mClientHostname = pClientHostname;
  }
}
